// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoIoNVXiVKBvmPXXGegSZHfXb4eImyTzM',
    appId: '1:162314490059:web:56861a7f3fd352a8610b4e',
    messagingSenderId: '162314490059',
    projectId: 'petbook-8daf6',
    authDomain: 'petbook-8daf6.firebaseapp.com',
    databaseURL: 'https://petbook-8daf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petbook-8daf6.appspot.com',
    measurementId: 'G-QJMYYLGVXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVq7_-xLyfI49aBS4ZCvoVgS7PY9OGZqQ',
    appId: '1:162314490059:android:9a6434d753797442610b4e',
    messagingSenderId: '162314490059',
    projectId: 'petbook-8daf6',
    databaseURL: 'https://petbook-8daf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petbook-8daf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuDu2ZL5Ro64JOBjLXgWvQi92zta53ZXY',
    appId: '1:162314490059:ios:c2f0fb04c4b0d0b5610b4e',
    messagingSenderId: '162314490059',
    projectId: 'petbook-8daf6',
    databaseURL: 'https://petbook-8daf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petbook-8daf6.appspot.com',
    androidClientId: '162314490059-44tdsoau5p0m70urs2fvc464r5upih7k.apps.googleusercontent.com',
    iosClientId: '162314490059-0cl3ipjvuh7u7glgsi5b821a0lp5adad.apps.googleusercontent.com',
    iosBundleId: 'com.example.petbook',
  );
}
